# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.IntegerField(max_length=1, verbose_name='TYPE')),
                ('record_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='RECORD_TIMESTAMP')),
                ('call_id', models.IntegerField(verbose_name='CALL_IDENTIFIER')),
                ('source', models.IntegerField(max_length=9, verbose_name='SOURCE')),
                ('destination', models.IntegerField(max_length=9, verbose_name='DESTINATION')),
            ],
        ),
    ]
