# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Calls',
            },
        ),
        migrations.CreateModel(
            name='CallBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=9, verbose_name='PRICE')),
                ('duration', models.DateTimeField(auto_now_add=True, verbose_name='DURATION')),
                ('call', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Call')),
            ],
        ),
        migrations.CreateModel(
            name='StartCallRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('record_timestamp', models.DateTimeField(verbose_name='RECORD_TIMESTAMP')),
                ('source', models.IntegerField(max_length=9, verbose_name='SOURCE')),
                ('destination', models.IntegerField(max_length=9, verbose_name='DESTINATION')),
                ('call', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Call')),
            ],
            options={
                'db_table': 'Starts',
            },
        ),
        migrations.CreateModel(
            name='StopCallRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('record_timestamp', models.DateTimeField(verbose_name='RECORD_TIMESTAMP')),
                ('call', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Call')),
            ],
            options={
                'db_table': 'Stops',
            },
        ),
    ]
