# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-05 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbills',
            name='duration',
            field=models.DurationField(verbose_name='DURATION'),
        ),
    ]
