# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='CREATE_DATE'),
        ),
    ]
