# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190811_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.IntegerField(verbose_name='DESTINATION'),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.IntegerField(verbose_name='SOURCE'),
        ),
        migrations.AlterField(
            model_name='callbills',
            name='price',
            field=models.IntegerField(verbose_name='PRICE'),
        ),
    ]
