# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190812_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.BigIntegerField(verbose_name='DESTINATION'),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.BigIntegerField(verbose_name='SOURCE'),
        ),
    ]
