# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200428_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charges',
            unique_together=set([('standing_charge', 'call_charge')]),
        ),
    ]
