# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-29 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200428_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='status',
        ),
        migrations.AddField(
            model_name='charges',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ACTIVE'),
            preserve_default=False,
        ),
    ]
