# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200429_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='PRICE')),
            ],
            options={
                'db_table': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_charge', models.FloatField(max_length=9, verbose_name='STANDING_CHARGE')),
                ('call_charge', models.FloatField(verbose_name='CALL_CHARGE')),
                ('charge_start', models.IntegerField(verbose_name='STANDARD_START')),
                ('charge_stop', models.IntegerField(verbose_name='STANDARD_STOP')),
                ('active', models.BooleanField(verbose_name='ACTIVE')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='CREATE_DATE')),
            ],
            options={
                'db_table': 'Charge',
            },
        ),
        migrations.RemoveField(
            model_name='callbills',
            name='call',
        ),
        migrations.DeleteModel(
            name='Charges',
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.CharField(default=1, max_length=10, verbose_name='DURATION'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='call',
            table='Call',
        ),
        migrations.DeleteModel(
            name='CallBills',
        ),
        migrations.AlterUniqueTogether(
            name='charge',
            unique_together=set([('standing_charge', 'call_charge')]),
        ),
        migrations.AddField(
            model_name='bill',
            name='call',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Call'),
        ),
    ]
