# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-29 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200429_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='charge_start',
            new_name='hour_start',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='charge_stop',
            new_name='hour_stop',
        ),
    ]
