# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200429_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.FloatField(verbose_name='PRICE'),
        ),
    ]
