# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200429_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Call'),
        ),
    ]
