# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-30 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200430_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='call',
        ),
        migrations.AddField(
            model_name='call',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Bill'),
            preserve_default=False,
        ),
    ]
