# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200430_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Charge'),
            preserve_default=False,
        ),
    ]
