# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-30 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200430_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_call', to='api.Call'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_charge', to='api.Charge'),
        ),
        migrations.AlterModelTable(
            name='bill',
            table='bill',
        ),
        migrations.AlterModelTable(
            name='call',
            table='call',
        ),
        migrations.AlterModelTable(
            name='charge',
            table='charge',
        ),
    ]
