# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200508_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_charge', to='api.Charge'),
        ),
    ]
